name: Deploy MkDocs project to Github pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build site
        run: mkdocs build
        
      - name: Upload production artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site  # MkDocs saves the HTML here

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
